version = 0.1

[default.deploy.parameters]
stack_name = "dev-impulsame-backend"
s3_bucket = "sam-artifacts-dev-impulsame"
s3_prefix = "backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
confirm_changeset = false
fail_on_empty_changeset = false

[dev.deploy.parameters]
stack_name = "dev-impulsame-backend"
s3_bucket = "sam-artifacts-dev-impulsame"
s3_prefix = "backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
confirm_changeset = false
fail_on_empty_changeset = false

[main.deploy.parameters]
stack_name = "main-impulsame-backend"
s3_bucket = "sam-artifacts-main-impulsame"
s3_prefix = "backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=main"
confirm_changeset = false
fail_on_empty_changeset = false
