version = 0.1

[default.deploy.parameters]
stack_name = "dev-impulsame-backend"
s3_bucket = "sam-artifacts-dev-impulsame"
s3_prefix = "backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
confirm_changeset = false
fail_on_empty_changeset = false

[dev.deploy.parameters]
stack_name = "dev-impulsame-backend"
s3_bucket = "sam-artifacts-dev-impulsame"
s3_prefix = "backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=dev",
    "DbHost=TU_DB_HOST_DEV",
    "DbUser=TU_DB_USER_DEV", 
    "DbPass=TU_DB_PASS_DEV",
    "DbName=impulsame_dev",
    "VpcId=vpc-07a2057b856abc88a",
    "SubnetId1=subnet-0a4c6ec40547ef6bc",
    "SubnetId2=",
    "SubnetId3=",
    "SecurityGroupId=sg-041ca83b054423bae"
]
confirm_changeset = false
fail_on_empty_changeset = false

[main.deploy.parameters]
stack_name = "main-impulsame-backend"
s3_bucket = "sam-artifacts-main-impulsame"
s3_prefix = "backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "Environment=main",
    "DbHost=TU_DB_HOST_MAIN",
    "DbUser=TU_DB_USER_MAIN",
    "DbPass=TU_DB_PASS_MAIN", 
    "DbName=impulsame_main",
    "VpcId=vpc-07a2057b856abc88a",
    "SubnetId1=subnet-0a4c6ec40547ef6bc",
    "SubnetId2=",
    "SubnetId3=",
    "SecurityGroupId=sg-041ca83b054423bae"
]
confirm_changeset = false
fail_on_empty_changeset = false
