AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Impulsame Backend API - Lambdas Outside VPC

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, main]
    Default: dev
    Description: Environment name (dev or main)
  UserDocumentsBucketName:
    Type: String
    Description: Name of the existing S3 bucket for user documents
  UserDocumentsBucketArn:
    Type: String
    Description: ARN of the existing S3 bucket for user documents
  ApiGatewayId:
    Type: String
    Description: ID of the existing API Gateway

Globals:
  Function:
    Timeout: 30
    Runtime: python3.13
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
    # NO VPC Config en Globals para este template

Resources:
  # Función Lambda: Request Files Get Upload URLs (SIN VPC)
  RequestFilesGetUploadUrlsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-request-files-get-upload-urls"
      CodeUri: lambdas/request-files-get-upload-urls/
      Handler: app.lambda_handler
      Runtime: python3.13
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          S3_BUCKET_NAME: !Ref UserDocumentsBucketName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectAcl
                - s3:GetObject
              Resource: !Sub "${UserDocumentsBucketArn}/*"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Events:
        GetUploadUrls:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayId
            Path: /request/files/get-upload-urls
            Method: POST
        OptionsRequest:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayId
            Path: /request/files/get-upload-urls
            Method: OPTIONS

Outputs:
  RequestFilesGetUploadUrlsFunction:
    Description: "Request Files Get Upload URLs Lambda Function ARN"
    Value: !GetAtt RequestFilesGetUploadUrlsFunction.Arn
    Export:
      Name: !Sub "${Environment}-request-files-get-upload-urls-function-arn"

  RequestFilesGetUploadUrlsApi:
    Description: "API Gateway endpoint URL for Request Files Get Upload URLs function"
    Value: !Sub "https://${ApiGatewayId}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/request/files/get-upload-urls"
    Export:
      Name: !Sub "${Environment}-request-files-get-upload-urls-api-url"
